### ISSUE TITLE
Adding problem statement to the solutions file

### ISSUE THREAD

**Issue by Harshpatel44** [mistryvatsal/Leetcode-30-Days-Code-Challenge-April-2020#1]
Hi Vatsal, it would be better if the solution files also have the problem statements. Otherwise, the person will have to check the problem statements from the website. This will make things easier for them

**Comment by mistryvatsal** [comment]
Hi @Harshpatel44, yes I'm planning to add the same. Soon will add the problem statements and constraints.

**Comment by mistryvatsal** [comment]
Hi @Harshpatel44 . I have added brief/description about the problem in txt files.
Hence closing the issue now.
